backend:
  name: git-gateway
  branch: master
  repo: johanbissemattsson/sorenholst-se
  site_domain: location.hostname

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    folder: 'src/pages'
    filter: {field: 'templateKey', value: 'page'}
    extension: 'md'
    slug: '{{slug}}'
    create: true
    editor:
      preview: false    
    fields:
      - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'page'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
      - {label: 'Info box', name: 'bodyBox', widget: 'markdown', required: false}
      - {label: 'Extra content', name: 'bodyExtra', widget: 'markdown', required: false}
      - label: 'List content (with images)'
        name: 'list'
        widget: 'list'
        required: false
        fields:
          - {label: 'List item title', name: 'listItemTitle', widget: 'string'}
          - {label: 'List item content', name: 'listItemContent', widget: 'markdown', required: false}
          - {label: 'List item image', name: 'listItemImage', widget: 'image', required: false}
          - {label: 'List item link', name: 'listItemLink', widget: 'string', required: false}
  - name: 'index'
    label: 'Index Page'
    folder: 'src/pages'
    filter: {field: 'templateKey', value: 'index-page'}
    extension: 'md'
    slug: '{{slug}}'
    editor:
      preview: false    
    fields:
      - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'index-page'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Subtitle', name: 'subtitle', widget: 'string'}
      - {label: 'Description', name: 'description', widget: 'markdown'}
      - {label: 'Portrait image', name: 'portraitImage', widget: 'image'}
      - {label: 'Body', name: 'body', widget: 'hidden'}
      - label: 'Sections'
        name: 'sections'
        widget: 'list'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Description', name: 'description', widget: 'markdown'}
          - {label: 'UID (used for anchor links)', name: 'uid', widget: 'string', required: false}          
          - label: 'Section items'
            name: 'sectionItems'
            widget: 'list'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Description', name: 'description', widget: 'markdown'}
              - {label: 'Link', name: 'link', widget: 'string', required: false}
              - label: 'Featured image'
                name: 'featuredImage'
                widget: 'object'
                required: false
                fields:
                  - {label: 'Image', name: 'src', widget: 'image'}
                  - {label: 'Image alt text', name: 'alt', widget: 'string'}
          - {label: 'Content under section items', name: 'more', widget: 'markdown', required: false}
                  